{!! field()->number('followers', __('influencer::dashboard.instagram.form.followers')) !!}
{!! field()->number('posts_count', __('influencer::dashboard.instagram.form.posts_count')) !!}
{!! field()->text('avg_likes', __('influencer::dashboard.instagram.form.avg_likes')) !!}
{!! field()->text('avg_views', __('influencer::dashboard.instagram.form.avg_views')) !!}
{!! field()->text('audience_credibility', __('influencer::dashboard.instagram.form.audience_credibility')) !!}
{!! field()->text('avg_reels_plays', __('influencer::dashboard.instagram.form.avg_reels_plays')) !!}
{!! field()->text('posts_with_hidden_likes_percentage', __('influencer::dashboard.instagram.form.posts_with_hidden_likes_percentage')) !!}
{!! field()->text('engagement_rate', __('influencer::dashboard.instagram.form.engagement_rate')) !!}
{!! field()->text('engagements', __('influencer::dashboard.instagram.form.engagements')) !!}
{!! field()->text('quality_score', __('influencer::dashboard.instagram.form.quality_score')) !!}
{!! field()->checkBox('is_business', __('influencer::dashboard.instagram.form.is_business')) !!}
{!! field()->checkBox('is_hidden', __('influencer::dashboard.instagram.form.is_hidden')) !!}
{!! field()->checkBox('is_verified', __('influencer::dashboard.instagram.form.is_verified')) !!}
{!! field()->text('avg_comments', __('influencer::dashboard.instagram.form.avg_comments')) !!}
